name: M5 Kiosque Workflow

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Kiosque Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install pytest pytest-testdox
      - name: Run Tests
        run: pytest --force-testdox -vvs